"""add_manuscript_model

Revision ID: 24fc296a2de1
Revises: 2dec90e74d12
Create Date: 2026-06-04 21:16:19.419485+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24fc296a2de1'
down_revision: Union[str, None] = '2dec90e74d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manuscripts',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_latex', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('compiled_url', sa.Text(), nullable=True),
    sa.Column('bibtex', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscripts_id'), 'manuscripts', ['id'], unique=False)
    op.create_index(op.f('ix_manuscripts_project_id'), 'manuscripts', ['project_id'], unique=False)
    op.create_index(op.f('ix_manuscripts_run_id'), 'manuscripts', ['run_id'], unique=False)
    # op.add_column('papers', sa.Column('references', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('papers', 'references')
    op.drop_index(op.f('ix_manuscripts_run_id'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_project_id'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_id'), table_name='manuscripts')
    op.drop_table('manuscripts')
    # ### end Alembic commands ###
